### ISSUE TITLE
Blank_scope error

### ISSUE THREAD

**Issue by vblinden** [SocialiteProviders/Slack#2]
When I execute the following: `return Socialite::driver('slack')->redirect();`.

I get the following error, apparently you need to add scopes to the url (https://api.slack.com/docs/oauth-scopes). Am I doing something wrong here?

`OAuth error: blank_scope: Requested scopes cannot be blank`

I have followed the guide and set up the client id, secret and redirect url.

Thanks in advance.

**Comment by AndyWendt** [comment]
It sounds like you need to add some scopes with your request.  See here on how to do that: https://github.com/laravel/socialite

You will need to look at the slack docs for what scopes you need to provide.

**Comment by vblinden** [comment]
How stupid of me to read over it. Thanks a lot for the help.

**Comment by AndyWendt** [comment]
No problem :smile:
