### ISSUE TITLE
Call to undefined method SocialiteProviders\Slack\Provider::parseAccessToken()

### ISSUE THREAD

**Issue by Taras-S** [SocialiteProviders/Slack#7]
All settings is correct, but i get this error. I checked code, there is no this method at all, but it called in
vendor/socialiteproviders/manager/src/OAuth2/AbstractProvider.php on line 59.

**Comment by DraperStudio** [comment]
Update your packages, the method exists. https://github.com/SocialiteProviders/Manager/blob/master/src/OAuth2/AbstractProvider.php#L52-L62

**Comment by Taras-S** [comment]
This packages require "socialiteproviders/manager": "~2.0". In Manager 2.0 there is no method ''parseAccessToken()"

**Comment by Taras-S** [comment]
Solved by upgrading to last version. But now i getting #8
